
* START

  The START Natural Language System is a software system designed
  to answer questions that are posed to it in natural
  language. START parses incoming questions, matches the queries
  created from the parse trees against its knowledge base and
  presents the appropriate information segments to the user. In
  this way, START provides untrained users with speedy access to
  knowledge that in many cases would take an expert some time to
  find.

  START (SynTactic Analysis using Reversible Transformations) was
  developed by Boris Katz at MIT's Artificial Intelligence
  Laboratory. Currently, the system is undergoing further development by
  the InfoLab Group, led by Boris Katz. START was first connected to the
  World Wide Web in December, 1993, and in its several forms has to date
  answered millions of questions from users around the world.

  A key technique called "natural language annotation" helps START
  connect information seekers to information sources. This technique
  employs natural language sentences and phrases annotations as
  descriptions of content that are associated with information
  segments at various granularities. An information segment is
  retrieved when its annotation matches an input question. This
  method allows START to handle all variety of media, including
  text, diagrams, images, video and audio clips, data sets, Web
  pages, and others.

  The natural language processing component of START consists of two
  modules that share the same grammar. The understanding module analyzes
  English text and produces a knowledge base that encodes information
  found in the text. Given an appropriate segment of the knowledge base,
  the generating module produces English sentences. Used in conjunction
  with the technique of natural language annotation, these modules put
  the power of sentence-level natural language processing to use in the
  service of multi-media information access.

* Omnibase, wikipedia, wikipediabase and wikipedia mirror


  Omnibase is a "virtual" database that provides a uniform interface
  to multiple Web knowledge sources, capable of executing the struc-
  tured queries generated by START. Omnibase was first developed in
  2002, at about the same time when wikipedia made it's first
  appearance (2001).

  The online encyclopedia Wikipedia is a vast, constantly evolving
  tapestry of richly interlinked textual information.  To a growing
  community of researchers and developers it is an ever-growing source
  of manually defined concepts and semantic relations. It constitutes
  an unparalleled and largely untapped resource for natural language
  processing, knowledge management, data mining, and other research
  areas. It is the product of the collaborative work of millions of
  people. Wikipedia is based on the wiki [refrence] system, a category
  of websites that allow for collaborative modification of content.

  Due to the complexity and the highly unstructured nature of
  wikipedia instead of an omnibase backend START uses a separate
  service, WikipediaBase, the subject of this thesis. Also to avoid
  flooding wikiedpedia.org we developed wikipedia mirror to crate a
  clone of wikipedia for WikipediaBase to use.
