
* START

  START (SynTactic Analysis using Reversible Transformations) is a
  system designed to answer questions posed in natural language,
  favoring precision over recall. It was developed by Boris Katz at
  MiT's Artificial Intelligence Laboratory and surfaced the internet
  in December 1993. The basic premise of it's functionality is that it
  normalizes questions into internal representations that it matches
  against it's knowledge base to present the user with an accurate
  answer. Currently START is developed and maintained by InfoLab, led
  by Boris Katz.

  The central technique employed by START to draw connections between
  natural language queries and their answers is called "natural
  language annotation". According to this method data is annotated
  with natural language phrases and sentences and then matched with
  the input question. This allows the START user to access arbitrary
  media types with natural language including text, diagrams, images,
  video and audio clips, data sets and Web pages.

  For natural language annotation to be useful two modules come into
  play, the understanding module and the generating module. The
  understanding module produces a knowledge base encoding information
  from a given english text. The generating module can generate
  natural language from segments of the knowledge base. Finally these
  two modules are provided with a natural language interface to
  multi-media information by natural language annotation.

* Omnibase, wikipedia, wikipediabase and wikipedia mirror


  Omnibase is a "virtual" database that provides a uniform interface
  to multiple Web knowledge sources, capable of executing the struc-
  tured queries generated by START. Omnibase was first developed in
  2002, at about the same time when wikipedia made it's first
  appearance (2001).

  The online encyclopedia Wikipedia is a vast, constantly evolving
  tapestry of richly interlinked textual information.  To a growing
  community of researchers and developers it is an ever-growing source
  of manually defined concepts and semantic relations. It constitutes
  an unparalleled and largely untapped resource for natural language
  processing, knowledge management, data mining, and other research
  areas. It is the product of the collaborative work of millions of
  people. Wikipedia is based on the wiki [refrence] system, a category
  of websites that allow for collaborative modification of content.

  Due to the complexity and the highly unstructured nature of
  wikipedia instead of an omnibase backend START uses a separate
  service, WikipediaBase, the subject of this thesis. Also to avoid
  flooding wikiedpedia.org we developed wikipedia mirror to crate a
  clone of wikipedia for WikipediaBase to use.
