#+TITLE:       Extracting relational data from Wikipedia
#+AUTHOR:      Chris Perivolaropoulos
#+DATE:        Sunday 21 February 2016
#+EMAIL:       cperivol@csail.mit.edu
#+DESCRIPTION: Making sense of semi structured data in wikipedia.
#+KEYWORDS:
#+LANGUAGE:    en
#+OPTIONS:     H:2 num:t toc:t \n:nil @:t ::t |:t ^:t f:t TeX:t
#+STARTUP:     showall

* Acknowledgements

* Abstract

  MiT InfoLab's START (SynTactic Analysis using Reversible
  Transformations) is the worlds first question answering system. It
  was developed in the early 80s and went online in 1993. For
  accessing most data sources it takes advantage of, START depends on
  Omnibase, the /"virtual database"/ providing uniform access to
  multiple sources on the web. Wikipedia surfaced at about the same
  time as Omnibase, during the early 00s, and did not gain popularity
  until the mid 00s. So, while wikipedia can provide a vast amount of
  information, Omnibase does not include it in it's data sources. Our
  work is divided in two parts: WikipediaBase, and wikipedia
  mirror. WikipediaBase provides START access to information in
  wikipedia with an interface similar to Omnibase's. Wikipedia mirror
  is a program that automates the creation of wikipedia.org mirrors on
  a local machine, to provide control and unrestricted access to the
  dataset without depending or abusing wikipedia.org.

* Introduction
  #+INCLUDE: "./introduction.org"
* Wikipediabase
  #+INCLUDE: "./wikipediabase/index.org"
* WikipediaMirror
  #+INCLUDE: "./wikipediamirror/index.org"
* Related CSAIL projects
  # See github
* Conclusion
